version: '3'
services:
    mysql:
        image: 'mysql:5.7.32'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: '%'
        volumes:
            - 'infra-mysql:/var/lib/mysql'
            - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
        networks:
            - infra
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-proot'
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
            - '9000:80'
        networks:
            - infra
        links:
            - 'mysql:db'
        environment:
            UPLOAD_LIMIT: 2G
        depends_on:
            - mysql
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'infra-redis:/data'
        networks:
            - infra
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
networks:
    infra:
        driver: bridge
volumes:
    infra-mysql:
        driver: local
    infra-redis:
        driver: local
